Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Controllers/OrderController.cs
namespace Web.Controllers
{
    using System.Web.Mvc;

    public class OrderController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Example MVC order system</h2>

<p>The application uses a .NET Core Web API as a data source to populate a simple order system.</p>
<p>Click the 'Your Orders' link above to be taken to the order list.</p>
<p>The order is list is populated by an Ajax call to the server and is rendered in an accordion layout which can be expanded to show the details of the order.</p>

Web/Views/Order/Index.cshtml
@{
    ViewBag.Title = "Current Orders";
}

<h2>Your orders</h2>
<p>Click on an order to expand it and see the details of the items on it.</p>
<hr class="uk-divider-icon">
<ul uk-accordion id="orders-holder">
</ul>

@section Scripts {

<script>
    $(document).ready(function () {
        $OrderSystem.loadOrders();
    });
</script>
    
}

Web/Views/Order/Order.cshtml
<h1>Your Orders</h1>

Web/Views/Order/OrderDetails.cshtml
<h1>Your Order Details</h1>
<p>Order details for order ###</p>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en-gb">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- UIkit CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/uikit@3.6.15/dist/css/uikit.min.css" />

    <!-- UIkit JS -->
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.15/dist/js/uikit.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/uikit@3.6.15/dist/js/uikit-icons.min.js"></script>


    <title>Clothing Order System</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="uk-navbar-container" uk-navbar>
        <div class="uk-navbar-left">
            <ul class="uk-navbar-nav">
                <li><span class="uk-navbar-item uk-logo" href="#">Clothing Order System</span></li>
            </ul>
        </div>
        <div class="uk-navbar-right">
            <ul class="uk-navbar-nav">
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li><a href="@Url.Action("Index", "Order")">Your Orders</a></li>
            </ul>
        </div>
    </nav>

    <div class="uk-container uk-margin-top">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/OrderSystem")
    @RenderSection("scripts", required: false)
</body>
</html>